FROM node:8.9.0

RUN useradd --user-group --create-home --shell /bin/false app && npm install --global pm2

ENV HOME=/home/app
WORKDIR $HOME

ENV APP_NAME=server

COPY . $HOME/$APP_NAME/
RUN chown -R app:app $HOME/*

USER app

EXPOSE 4000

WORKDIR $HOME/$APP_NAME

CMD ["npm", "run" "start:prod"]
